/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ControlRouteImport } from './routes/control'
import { Route as BluetoothRouteImport } from './routes/bluetooth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSensorReadingRouteImport } from './routes/api.sensor-reading'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram.webhook'
import { Route as ApiTelegramSetupRouteImport } from './routes/api.telegram.setup'
import { Route as ApiPublicResetStateRouteImport } from './routes/api.public.reset-state'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api.public.telegram.webhook'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const BluetoothRoute = BluetoothRouteImport.update({
  id: '/bluetooth',
  path: '/bluetooth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSensorReadingRoute = ApiSensorReadingRouteImport.update({
  id: '/api/sensor-reading',
  path: '/api/sensor-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupRoute = ApiTelegramSetupRouteImport.update({
  id: '/api/telegram/setup',
  path: '/api/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetStateRoute = ApiPublicResetStateRouteImport.update({
  id: '/api/public/reset-state',
  path: '/api/public/reset-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bluetooth': typeof BluetoothRoute
  '/control': typeof ControlRoute
  '/history': typeof HistoryRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
  '/api/public/reset-state': typeof ApiPublicResetStateRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bluetooth': typeof BluetoothRoute
  '/control': typeof ControlRoute
  '/history': typeof HistoryRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
  '/api/public/reset-state': typeof ApiPublicResetStateRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bluetooth': typeof BluetoothRoute
  '/control': typeof ControlRoute
  '/history': typeof HistoryRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
  '/api/public/reset-state': typeof ApiPublicResetStateRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bluetooth'
    | '/control'
    | '/history'
    | '/api/sensor-reading'
    | '/api/public/reset-state'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bluetooth'
    | '/control'
    | '/history'
    | '/api/sensor-reading'
    | '/api/public/reset-state'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/bluetooth'
    | '/control'
    | '/history'
    | '/api/sensor-reading'
    | '/api/public/reset-state'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BluetoothRoute: typeof BluetoothRoute
  ControlRoute: typeof ControlRoute
  HistoryRoute: typeof HistoryRoute
  ApiSensorReadingRoute: typeof ApiSensorReadingRoute
  ApiPublicResetStateRoute: typeof ApiPublicResetStateRoute
  ApiTelegramSetupRoute: typeof ApiTelegramSetupRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bluetooth': {
      id: '/bluetooth'
      path: '/bluetooth'
      fullPath: '/bluetooth'
      preLoaderRoute: typeof BluetoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sensor-reading': {
      id: '/api/sensor-reading'
      path: '/api/sensor-reading'
      fullPath: '/api/sensor-reading'
      preLoaderRoute: typeof ApiSensorReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup': {
      id: '/api/telegram/setup'
      path: '/api/telegram/setup'
      fullPath: '/api/telegram/setup'
      preLoaderRoute: typeof ApiTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-state': {
      id: '/api/public/reset-state'
      path: '/api/public/reset-state'
      fullPath: '/api/public/reset-state'
      preLoaderRoute: typeof ApiPublicResetStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BluetoothRoute: BluetoothRoute,
  ControlRoute: ControlRoute,
  HistoryRoute: HistoryRoute,
  ApiSensorReadingRoute: ApiSensorReadingRoute,
  ApiPublicResetStateRoute: ApiPublicResetStateRoute,
  ApiTelegramSetupRoute: ApiTelegramSetupRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
